src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuestionRepository::class)
 */
class Question
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $question;

    /**
     * @ORM\ManyToOne(targetEntity=Quiz::class, inversedBy="questions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Quiz;

    /**
     * @ORM\OneToMany(targetEntity=Answer::class, mappedBy="Question", orphanRemoval=true)
     */
    private $answers;

    /**
     * @ORM\ManyToMany(targetEntity=UserAnswer::class, mappedBy="question")
     */
    private $userAnswers;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
        $this->userAnswers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getQuiz(): ?Quiz
    {
        return $this->Quiz;
    }

    public function setQuiz(?Quiz $Quiz): self
    {
        $this->Quiz = $Quiz;

        return $this;
    }

    /**
     * @return Collection|Answer[]
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->contains($answer)) {
            $this->answers->removeElement($answer);
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|UserAnswer[]
     */
    public function getUserAnswers(): Collection
    {
        return $this->userAnswers;
    }

    public function addUserAnswer(UserAnswer $userAnswer): self
    {
        if (!$this->userAnswers->contains($userAnswer)) {
            $this->userAnswers[] = $userAnswer;
            $userAnswer->addQuestion($this);
        }

        return $this;
    }

    public function removeUserAnswer(UserAnswer $userAnswer): self
    {
        if ($this->userAnswers->contains($userAnswer)) {
            $this->userAnswers->removeElement($userAnswer);
            $userAnswer->removeQuestion($this);
        }

        return $this;
    }
}

src/Form/SurveyType.php
<?php

namespace App\Form;

use App\Entity\Quiz;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SurveyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            // ->add('answer')
            ->add('questions')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Quiz::class,
        ]);
    }
}

templates/survey/questions.html.twig
{% extends 'base.html.twig' %}

{% block title %}Survey for {{ categories.quiz_name }}{% endblock %}

{% block body %}
<h1>{{ categories.quiz_name }} Servey</h1>

{# {{ form_start(form) }}
        {{ form_widget(form) }}
 {{ form_end(form) }}    #}


<form action="{{ path("save_survey") }}" method="post">

    <input type="hidden" name="token" value="{{ csrf_token('survey_submit') }}" />
    <fieldset>
        {% for q_key, question in categories.questions %}
        <fieldset class="form-group">
            <legend>{{ question.question }}</legend>

            {% for key, answer in question.answers %}

            <div class="form-check">
                <label class="form-check-label">
                    <input type="radio" class="form-check-input" name="questions[{{ q_key }}]" value="{{ key }}"
                        required>
                    {{ answer }}
                </label>
            </div>

            {% endfor %}
        </fieldset>
        {% endfor %}

        <fieldset class="form-group">
            <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
        </fieldset>


    </fieldset>

</form>
{# {{ dump(form) }}

{{ dump(form.questions) }}
{# {{ form_start(form) }}
    {# {{ form_row(form.question) }} #}

{# <ul class="questions">
        {% for questions in form.quiz %}
            <li>{{ form_row(question.question) }}</li>
        {% endfor %}
    </ul>  #}

{# <h3>Answers</h3>
    <ul class="answers">
        {% for answer in form.answers %}
            <li>{{ form_row(answer.answer) }}</li>
        {% endfor %}
    </ul> 
{{ form_end(form) }}  #}


<br>
<a href="{{ path('homepage') }}">back to list</a>
{% endblock %}